# Generated by Django 6.0.1 on 2026-01-19 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.PositiveIntegerField(default=0)),
                ('group_id', models.CharField(blank=True, max_length=120)),
                ('next_review_time', models.DateTimeField(blank=True, null=True)),
                ('config', models.JSONField(default=dict)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='study.box')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='box',
            index=models.Index(fields=['user', 'created_at'], name='study_box_user_id_90f6ff_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['box', 'created_at'], name='study_card_box_id_879b50_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['box', 'finished'], name='study_card_box_id_cfc339_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['box', 'next_review_time'], name='study_card_box_id_caf628_idx'),
        ),
    ]
