# Generated by Django 6.0.1 on 2026-01-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_cardactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='share_code',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
