# Generated by Django 6.0.1 on 2026-01-19 23:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_box_share_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='box',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_box_name_per_user'),
        ),
    ]
