# Generated by Django 6.0.1 on 2026-02-01 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0008_exercise_history"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exercise",
            old_name="questions",
            new_name="exercises",
        ),
    ]
