# Generated by Django 6.0.1 on 2026-02-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0009_rename_questions_to_exercises"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercisehistory",
            name="score",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
