# Generated by Django 6.0.1 on 2026-02-01 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0010_exercisehistory_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="is_important",
            field=models.BooleanField(default=False),
        ),
    ]
